version: '3.8'
services:
  mosquitto:
    image: docker.io/eclipse-mosquitto:latest
    container_name: umbral-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:z
      - ./mosquitto/data:/mosquitto/data:z
    restart: unless-stopped
